enablePrimitiveVoidOre: false

disableMultiBlockPage: false

fastMultiBlockPage: true

recipeLogicCheckInterval: 20

oreMultiplier: 4

spacetimePip: 2147483647

eioFluidRate: 16

breakBlocksBlackList:
  - ae2:cable_bus

